name: Manual GitHub Flow

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  merge_dev_into_qa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Pull from origin dev
      run: git pull origin dev

    - name: Checkout qa
      run: git checkout qa

    - name: Pull from origin qa
      run: git pull origin qa

    - name: Merge dev into qa
      run: git merge dev

    - name: Push qa to origin qa
      run: git push origin qa

